name: Publish
on: { push: { branches: [ main, "0.20" ] }, release: { types: [ created ] } }

permissions:
  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - { name: Checkout, uses: actions/checkout@v6 }
    - { name: Setup Node.js environment, uses: actions/setup-node@v6, with: { node-version: 24 } }
    - { name: Setup pnpm, uses: pnpm/action-setup@v4, with: { run_install: true } }
    - run: git config --global user.email github-action@users.noreply.github.com
    - run: git config --global user.name "Github Action"
    - run: pnpm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
    - run: export PATH=$PWD/node_modules/.bin:$PATH

    - name: Publish dev
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run: scripts/version-dev.js && scripts/package.sh && cd dist && pnpm publish --no-git-checks --tag dev

    - name: Publish release
      if: github.event_name == 'release'
      run: scripts/package.sh && cd dist && pnpm publish --no-git-checks
