name: Test
on: { push: { branches: [ "*" ] }, pull_request: { branches: [ "*" ] } }

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - { name: Checkout, uses: actions/checkout@v6 }
    - { name: Setup Node.js environment, uses: actions/setup-node@v6, with: { node-version: 24 } }
    - { name: Setup pnpm, uses: pnpm/action-setup@v4, with: { run_install: true } }
    - run: echo $PWD/node_modules/.bin:$PATH > $GITHUB_PATH
    - run: scripts/package.sh
    - run: scripts/lint.sh
    - run: npx vitest run
